import type {
  Feature,
  Issue,
  Sprint,
  ProjectDoc,
  Review,
  HealthCheck,
  VCSStatus,
  ForgeConfig,
} from '@/types'

export const mockConfig: ForgeConfig = {
  workflow: {
    states: ['draft', 'ready', 'in-progress', 'review', 'done'],
  },
  template: { source: 'built-in' },
  reviews: { types: ['architecture', 'design', 'security', 'usability'] },
}

export const mockVCS: VCSStatus = {
  branch: 'feature/oauth',
  dirty: true,
  lastCommit: {
    hash: 'a3f8c21',
    message: 'Add OAuth callback handler',
    author: 'Alice',
    timestamp: '2026-04-10T09:15:00Z',
  },
}

export const mockFeatures: Feature[] = [
  {
    name: 'User Authentication',
    slug: 'user-authentication',
    status: 'review',
    assignee: 'Alice',
    points: 8,
    backlogPosition: 1,
    sprint: 'sprint-3',
    body: '## Summary\n\nImplement user authentication with email/password login, registration, and session management.\n\n## Acceptance Criteria\n\n- Users can register with email and password\n- Users can log in and receive a session token\n- Sessions expire after 24 hours of inactivity\n- Password reset flow via email\n\n## Technical Notes\n\nUse bcrypt for password hashing. JWT tokens for session management.',
    artifacts: [
      { name: 'auth-flow.png', size: 24576 },
      { name: 'api-spec.yaml', size: 3277 },
    ],
    createdAt: '2026-03-15T10:00:00Z',
    modifiedAt: '2026-04-08T14:30:00Z',
  },
  {
    name: 'OAuth Integration',
    slug: 'oauth-integration',
    status: 'in-progress',
    assignee: 'Bob',
    points: 5,
    backlogPosition: 2,
    sprint: 'sprint-3',
    body: '## Summary\n\nIntegrate OAuth 2.0 for third-party login support.\n\n## Acceptance Criteria\n\n- Users can log in via Google and GitHub\n- Existing accounts can link OAuth providers\n- Session management works identically to password auth\n\n## Technical Notes\n\nUse the `golang.org/x/oauth2` package. Store provider tokens encrypted at rest.',
    artifacts: [{ name: 'wireframe.png', size: 18432 }],
    createdAt: '2026-03-20T11:00:00Z',
    modifiedAt: '2026-04-09T16:45:00Z',
  },
  {
    name: 'Payment Processing',
    slug: 'payment-processing',
    status: 'ready',
    assignee: null,
    points: 13,
    backlogPosition: 3,
    sprint: 'sprint-3',
    body: '## Summary\n\nIntegrate Stripe for payment processing including subscriptions and one-time payments.\n\n## Acceptance Criteria\n\n- Users can add a payment method\n- Support monthly and annual subscription plans\n- Handle failed payments with retry logic\n- Generate invoices',
    artifacts: [],
    createdAt: '2026-03-22T09:00:00Z',
    modifiedAt: '2026-04-05T11:20:00Z',
  },
  {
    name: 'Email Notifications',
    slug: 'email-notifications',
    status: 'draft',
    assignee: 'Carol',
    points: 3,
    backlogPosition: 4,
    sprint: null,
    body: '## Summary\n\nSend transactional emails for key user events.\n\n## Events\n\n- Welcome email on registration\n- Password reset\n- Payment confirmation\n- Subscription renewal reminder',
    artifacts: [],
    createdAt: '2026-03-25T14:00:00Z',
    modifiedAt: '2026-04-01T10:00:00Z',
  },
  {
    name: 'Dashboard Analytics',
    slug: 'dashboard-analytics',
    status: 'draft',
    assignee: null,
    points: 8,
    backlogPosition: 5,
    sprint: null,
    body: '## Summary\n\nBuild an analytics dashboard showing key metrics.\n\n## Metrics\n\n- Daily/weekly/monthly active users\n- Revenue trends\n- Feature usage heatmap\n- Conversion funnel',
    artifacts: [],
    createdAt: '2026-03-28T09:00:00Z',
    modifiedAt: '2026-03-28T09:00:00Z',
  },
  {
    name: 'API Rate Limiting',
    slug: 'api-rate-limiting',
    status: 'done',
    assignee: 'Bob',
    points: 3,
    backlogPosition: null,
    sprint: 'sprint-2',
    body: '## Summary\n\nImplement rate limiting on all public API endpoints.\n\n## Implementation\n\nToken bucket algorithm with configurable limits per endpoint.',
    artifacts: [],
    createdAt: '2026-03-10T10:00:00Z',
    modifiedAt: '2026-04-02T17:00:00Z',
  },
  {
    name: 'File Upload System',
    slug: 'file-upload-system',
    status: 'done',
    assignee: 'Alice',
    points: 5,
    backlogPosition: null,
    sprint: 'sprint-2',
    body: '## Summary\n\nAllow users to upload files with validation and storage.\n\n## Constraints\n\n- Max 50MB per file\n- Allowed types: images, PDFs, documents\n- Store in S3-compatible object storage',
    artifacts: [],
    createdAt: '2026-03-08T10:00:00Z',
    modifiedAt: '2026-03-30T15:00:00Z',
  },
  {
    name: 'Search Functionality',
    slug: 'search-functionality',
    status: 'ready',
    assignee: 'Carol',
    points: 5,
    backlogPosition: 6,
    sprint: null,
    body: '## Summary\n\nFull-text search across all content types.\n\n## Requirements\n\n- Search features, issues, and project docs\n- Support filters by type and status\n- Results ranked by relevance',
    artifacts: [],
    createdAt: '2026-04-01T09:00:00Z',
    modifiedAt: '2026-04-03T11:00:00Z',
  },
]

export const mockIssues: Issue[] = [
  {
    name: 'Login Timeout on Slow Connections',
    slug: 'login-timeout-on-slow-connections',
    status: 'open',
    assignee: null,
    labels: ['bug', 'networking'],
    linkedFeature: 'user-authentication',
    sprint: 'sprint-3',
    body: '## Description\n\nUsers on slow connections experience a timeout during login before the server responds.\n\n## Steps to Reproduce\n\n1. Throttle network to 3G speeds\n2. Navigate to login page\n3. Enter valid credentials and submit\n4. Observe timeout error after 5 seconds\n\n## Expected Behavior\n\nLogin should complete within 30 seconds on slow connections.',
    artifacts: [{ name: 'network-log.har', size: 45000 }],
    createdAt: '2026-04-02T10:00:00Z',
    modifiedAt: '2026-04-08T11:00:00Z',
  },
  {
    name: 'Missing Validation on File Upload',
    slug: 'missing-validation-on-file-upload',
    status: 'open',
    assignee: 'Alice',
    labels: ['bug', 'security'],
    linkedFeature: 'file-upload-system',
    sprint: 'sprint-3',
    body: '## Description\n\nFile upload endpoint accepts files without size or type validation.\n\n## Steps to Reproduce\n\n1. Navigate to the upload page\n2. Select a 2GB file\n3. Upload succeeds without any error\n\n## Expected Behavior\n\nUploads should be limited to 50MB and restricted to allowed file types.',
    artifacts: [],
    createdAt: '2026-04-03T14:00:00Z',
    modifiedAt: '2026-04-07T09:30:00Z',
  },
  {
    name: 'Broken CSS on Settings Page',
    slug: 'broken-css-on-settings-page',
    status: 'closed',
    assignee: 'Bob',
    labels: ['bug', 'ui'],
    linkedFeature: null,
    sprint: 'sprint-2',
    body: '## Description\n\nThe settings page layout breaks on viewport widths between 768px and 1024px.\n\n## Fix\n\nAdjusted the grid template columns for the medium breakpoint.',
    artifacts: [],
    createdAt: '2026-03-20T11:00:00Z',
    modifiedAt: '2026-03-28T16:00:00Z',
  },
  {
    name: 'Password Reset Email Delayed',
    slug: 'password-reset-email-delayed',
    status: 'open',
    assignee: 'Carol',
    labels: ['bug'],
    linkedFeature: 'user-authentication',
    sprint: null,
    body: '## Description\n\nPassword reset emails take 5-10 minutes to arrive. Users expect near-instant delivery.\n\n## Investigation\n\nLikely caused by email queue processing interval. Need to reduce batch interval or switch to immediate dispatch.',
    artifacts: [],
    createdAt: '2026-04-05T09:00:00Z',
    modifiedAt: '2026-04-06T14:00:00Z',
  },
  {
    name: 'API Returns 500 on Empty Search',
    slug: 'api-returns-500-on-empty-search',
    status: 'open',
    assignee: null,
    labels: ['bug', 'api'],
    linkedFeature: 'search-functionality',
    sprint: null,
    body: '## Description\n\nSending a GET request to `/api/search?q=` returns a 500 Internal Server Error.\n\n## Expected Behavior\n\nShould return an empty results array with a 200 status.',
    artifacts: [],
    createdAt: '2026-04-07T10:00:00Z',
    modifiedAt: '2026-04-07T10:00:00Z',
  },
]

export const mockSprints: Sprint[] = [
  {
    name: 'Sprint 1',
    slug: 'sprint-1',
    status: 'completed',
    startDate: '2026-03-03',
    endDate: '2026-03-14',
    goal: 'Foundation — project setup, CI/CD, basic auth',
    capacity: 30,
    features: ['api-rate-limiting'],
    issues: [],
    body: '## Retrospective\n\nGood velocity. CI/CD pipeline took longer than estimated.',
  },
  {
    name: 'Sprint 2',
    slug: 'sprint-2',
    status: 'completed',
    startDate: '2026-03-17',
    endDate: '2026-03-28',
    goal: 'File uploads, rate limiting, bug fixes',
    capacity: 35,
    features: ['file-upload-system'],
    issues: ['broken-css-on-settings-page'],
    body: '## Retrospective\n\nCompleted all planned work. File upload system was well-scoped.',
  },
  {
    name: 'Sprint 3',
    slug: 'sprint-3',
    status: 'active',
    startDate: '2026-04-07',
    endDate: '2026-04-18',
    goal: 'Ship OAuth integration and resolve critical upload bugs',
    capacity: 40,
    features: ['user-authentication', 'oauth-integration', 'payment-processing'],
    issues: ['login-timeout-on-slow-connections', 'missing-validation-on-file-upload'],
    body: '',
  },
  {
    name: 'Sprint 4',
    slug: 'sprint-4',
    status: 'planning',
    startDate: '2026-04-21',
    endDate: '2026-05-02',
    goal: '',
    capacity: 40,
    features: [],
    issues: [],
    body: '',
  },
]

export const mockDocs: ProjectDoc[] = [
  {
    name: 'Project Brief',
    slug: 'project-brief',
    body: '# Project Brief\n\nForge is a lightweight project management tool built for agile teams embracing agentic engineering workflows.\n\n## Problem\n\nModern agile teams working with AI agents face a bookkeeping problem. Project documentation, feature definitions, and backlog management all need to be accessible to both humans and AI agents.\n\n## Solution\n\nA single Go binary with a web UI and CLI that reads and writes a filesystem-based project structure.',
    modifiedAt: '2026-03-15T10:00:00Z',
  },
  {
    name: 'Technical Docs',
    slug: 'technical-docs',
    body: '# Technical Documentation\n\n## Architecture\n\nForge uses a single Go binary with an embedded SPA frontend.\n\n## API\n\nAll API endpoints are RESTful and return JSON.\n\n### Endpoints\n\n- `GET /api/features` — List all features\n- `POST /api/features` — Create a feature\n- `GET /api/features/:slug` — Get feature details\n- `PUT /api/features/:slug` — Update a feature\n- `DELETE /api/features/:slug` — Delete a feature',
    modifiedAt: '2026-04-01T11:00:00Z',
  },
  {
    name: 'Personas',
    slug: 'personas',
    body: '# Personas\n\n## Product Owner (Pat)\n\nPat manages the product backlog and writes feature definitions. They use the web UI primarily and need a clear overview of what\'s in progress.\n\n## Engineer (Alex)\n\nAlex picks up features from the backlog and works on implementation. They prefer the CLI and use AI agents to assist with coding.\n\n## Pumpking (Sam)\n\nSam reviews completed features and merges them into the main branch. They need a clear view of what\'s in review.',
    modifiedAt: '2026-03-20T09:00:00Z',
  },
  {
    name: 'Roadmap',
    slug: 'roadmap',
    body: '# Roadmap\n\n## Phase 1 — Core (Current)\n\n- `forge init` with template support\n- Features: CRUD, backlog management, workflow status\n- Issues: CRUD, basic metadata\n- Project docs: CRUD\n- Reviews: browse guidance docs\n- Web UI and CLI with full parity\n\n## Phase 2 — Enhancements\n\n- ADRs as a new entity type\n- Review-to-feature linking\n- Cloud deployment model\n- Enhanced git integration',
    modifiedAt: '2026-04-05T14:00:00Z',
  },
  {
    name: 'Design Docs',
    slug: 'design-docs',
    body: '# Design Documentation\n\n## Visual Language\n\nClean and minimal. Muted colors, generous whitespace. Content-focused.\n\n## Component Library\n\nUsing shadcn/ui with Tailwind CSS for consistent, accessible components.',
    modifiedAt: '2026-04-03T16:00:00Z',
  },
]

export const mockReviews: Review[] = [
  {
    type: 'Architecture',
    slug: 'architecture',
    description: 'Architectural review checklist and guidance',
    body: '# Architecture Review\n\n## Purpose\n\nEnsure the system architecture supports current and future requirements.\n\n## Checklist\n\n- [ ] Service boundaries are well-defined\n- [ ] Data flow is documented\n- [ ] Error handling is consistent across services\n- [ ] Scaling strategy is documented\n- [ ] No circular dependencies between packages\n- [ ] API versioning strategy is in place',
  },
  {
    type: 'Security',
    slug: 'security',
    description: 'Security review checklist',
    body: '# Security Review\n\n## Purpose\n\nEnsure the application meets security standards before release.\n\n## Checklist\n\n- [ ] Authentication flows reviewed\n- [ ] Authorization checks on all endpoints\n- [ ] Input validation on all user-facing inputs\n- [ ] SQL injection protections verified\n- [ ] CSRF protections in place\n- [ ] Secrets management reviewed\n- [ ] Dependency vulnerability scan completed',
  },
  {
    type: 'Design',
    slug: 'design',
    description: 'Design review process and standards',
    body: '# Design Review\n\n## Purpose\n\nEnsure UI/UX consistency and accessibility.\n\n## Checklist\n\n- [ ] Follows design system tokens (colors, spacing, typography)\n- [ ] Responsive at all breakpoints\n- [ ] Keyboard navigable\n- [ ] Screen reader friendly\n- [ ] Loading and error states handled\n- [ ] Empty states are helpful',
  },
  {
    type: 'Usability',
    slug: 'usability',
    description: 'Usability review guidelines',
    body: '# Usability Review\n\n## Purpose\n\nValidate that the product is intuitive and efficient for all user types.\n\n## Checklist\n\n- [ ] New user can complete core tasks without documentation\n- [ ] Navigation is predictable\n- [ ] Feedback is immediate for all actions\n- [ ] Destructive actions require confirmation\n- [ ] Error messages are actionable',
  },
]

export const mockHealthChecks: HealthCheck[] = [
  { name: 'directory-structure', status: 'pass', message: 'forge/ directory structure is valid' },
  { name: 'config', status: 'pass', message: 'forge.yaml is valid' },
  { name: 'project-docs', status: 'warn', message: 'Missing recommended document: use-cases.md' },
  { name: 'feature-integrity', status: 'pass', message: 'All 8 features have valid FEATURE.md files' },
  { name: 'issue-integrity', status: 'pass', message: 'All 5 issues have valid ISSUE.md files' },
  { name: 'backlog-consistency', status: 'pass', message: 'backlog.md references are consistent' },
  { name: 'sprint-integrity', status: 'pass', message: 'All 4 sprints have valid SPRINT.md files' },
  { name: 'sprint-consistency', status: 'pass', message: 'Sprint references and dates are valid' },
  { name: 'workflow-states', status: 'pass', message: 'All feature statuses match configured workflow' },
]

// Helper to compute sprint progress
export function getSprintProgress(sprint: Sprint) {
  const sprintFeatures = mockFeatures.filter((f) => sprint.features.includes(f.slug))
  const totalPoints = sprintFeatures.reduce((sum, f) => sum + (f.points ?? 0), 0)
  const completedPoints = sprintFeatures
    .filter((f) => f.status === 'done')
    .reduce((sum, f) => sum + (f.points ?? 0), 0)
  return { totalPoints, completedPoints, featureCount: sprint.features.length, issueCount: sprint.issues.length }
}
